# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mlpub < Formula
  desc "Deploy machine learning models with one command. ML Pub provides you with an easy way to deploy machine learning models easily."
  homepage "https://github.com/Emmarex/mlpub"
  version "0.0.1-beta"
  license "Apache"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Emmarex/mlpub/releases/download/v0.0.1-beta/mlpub_0.0.1-beta_macOS-ARM64.tar.gz"
      sha256 "5feb86b15a17a2f52f0eec0a80175ac6bb780107f786f8ad80b1a1be9b57c391"

      def install
        bin.install "mlpub"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Emmarex/mlpub/releases/download/v0.0.1-beta/mlpub_0.0.1-beta_macOS-64bit.tar.gz"
      sha256 "d8e0caf6739be17bd5ce810322211723ac441944e3c42355915b032addfca7ee"

      def install
        bin.install "mlpub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emmarex/mlpub/releases/download/v0.0.1-beta/mlpub_0.0.1-beta_Linux-ARM64.tar.gz"
      sha256 "fb8c65363440179cee53d091297ce784dc4b33a01e10fb9970a8f48d9b5fea9d"

      def install
        bin.install "mlpub"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Emmarex/mlpub/releases/download/v0.0.1-beta/mlpub_0.0.1-beta_Linux-64bit.tar.gz"
      sha256 "63ed1175a247013f71527a3906c24e64706104fade68d1d918927cd66e05cccf"

      def install
        bin.install "mlpub"
      end
    end
  end
end
